-- ============================================================================
--  20260715000300_poptavky.sql
--  Modul Poptávky. Předloha: Popt-vky/prisma/schema.prisma
--  (Inquiry, Comment, StatusLog + enum InquiryStatus).
--  Změny proti originálu:
--   - Person → profiles: inquiry.person_id odkazuje na profiles(id).
--   - stavy zachovány 1:1 (NOVA … ZAMITNUTO).
-- ============================================================================

create table inquiries (
  id               uuid primary key default gen_random_uuid(),
  number           bigint generated by default as identity unique, -- krátké pořadové číslo (#1, #2…)
  received_at      timestamptz not null default now(),
  subject          text not null,
  description      text,
  source           text,                        -- Mail / Telefon / Přímé oslovení
  contact_name     text,                         -- obchodník, který poptával
  contact_phone    text,
  contact_email    text,
  status           text not null default 'NOVA'
                     check (status in ('NOVA','V_JEDNANI','ODESLANA','NEREAGUJE','OBJEDNANO','ZAMITNUTO')),
  deadline         timestamptz,                  -- termín pro vypracování nabídky

  customer_id      uuid not null references customers (id) on delete restrict,
  person_id        uuid not null references profiles (id)  on delete restrict, -- dřívější Person

  -- Příznaky notifikací (v Poptávkách existovaly; v ERP se maily neposílají,
  -- pole ale ponecháváme kvůli 1:1 migraci historických dat).
  reminder_sent    boolean not null default false,
  expired_notified boolean not null default false,
  needs_contact    boolean not null default false,

  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index inquiries_status_idx    on inquiries (status);
create index inquiries_deadline_idx  on inquiries (deadline);
create index inquiries_person_id_idx on inquiries (person_id);

create trigger inquiries_set_updated_at
  before update on inquiries
  for each row execute function set_updated_at();

-- Komentář / poznámka k poptávce.
-- Autor zůstává volným textem (jako v originále, nebyl vázán na účet).
create table comments (
  id         uuid primary key default gen_random_uuid(),
  inquiry_id uuid not null references inquiries (id) on delete cascade,
  text       text not null,
  author     text not null,
  created_at timestamptz not null default now()
);

create index comments_inquiry_id_idx on comments (inquiry_id);

-- Historie změn stavu poptávky.
create table status_logs (
  id          uuid primary key default gen_random_uuid(),
  inquiry_id  uuid not null references inquiries (id) on delete cascade,
  from_status text
                check (from_status in ('NOVA','V_JEDNANI','ODESLANA','NEREAGUJE','OBJEDNANO','ZAMITNUTO')),
  to_status   text not null
                check (to_status in ('NOVA','V_JEDNANI','ODESLANA','NEREAGUJE','OBJEDNANO','ZAMITNUTO')),
  changed_by  text not null,
  note        text,
  created_at  timestamptz not null default now()
);

create index status_logs_inquiry_id_idx on status_logs (inquiry_id);
